#!/bin/bash



# source ~/.fzf.sh

export TERM="screen-256color"
export PATH=.:$PATH
export PATH_TO_FX=/usr/share/openjfx/lib
export PATH_TO_FX_MODS=/usr/share/openjfx/jmods
export RUSTFLAGS="$RUSTFLAGS -A dead_code"

export work=~/work
export memo=~/.local/daw/memo
export daw=~/.local/daw
export lib=~/.local/daw/cpp/lib
export olp=~/.local/daw/cpp/olp
export bin=~/.bin
export vimrc=~/.config/nvim/init.vim
export vim=~/.config/nvim
export inp=~/.local/initproj

export fit='std@std-1416.ist.mospolytech.ru'
export sph='a0566996@a0566996.xsph.ru'
export sc21="$HOME/.local/daw/sc21/42"
export sirius=~/work/sirius/yandex_intensive
export coinmind=~/.local/android/coinmind

# clang
export CPATH='/usr/include:/usr/local/include:/usr/include/c++/9:/usr/include/c++/9/backward:/usr/include/x86_64-linux-gnu/c++/9'
export LIBRARY_PATH=/usr/local/lib:/usr/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/x86_64-linux-gnu



# daw completion
_daw_completion() {
	COMPREPLY=()

	args=''
	if [ "$COMP_CWORD" -eq 1 ]
	then
		args="list push load mount turn move remove current"
	elif [ "$COMP_CWORD" -eq 2 ]
	then
		dir=`expr "${COMP_WORDS[COMP_CWORD]}" : '\(.*\)\/.*$'`
		if [ -n "$dir" ]
		then
			targs=`find "$HOME/.local/daw/$dir" -maxdepth 1 -mindepth 1 -type d`
			for arg in $targs
			do
				dir=`expr $arg : "$HOME\/\.local\/daw\/\(.*\)$"`
				args+="$dir/ "
			done
		else
			targs=`find "$HOME/.local/daw/" -maxdepth 1 -mindepth 1 -type d`
			for arg in $targs
			do
				dir=`expr $arg : '^.*\/\.local\/daw\/\(.*\)$'`
				args+="$dir/ "
			done
		fi
		# echo $args
	fi

	COMPREPLY=( $(compgen -W "${args}" -- ${COMP_WORDS[COMP_CWORD]}) )
	return 0
}

# complete -o bashdefault -o default -F _fzf_path_completion *
complete -F _daw_completion daw



# END
